### ISSUE TITLE
Can't copy files to free version of miro

### ISSUE THREAD

**Issue by tomf87** [vickytnz/govuk-elements-miro#2]
Hi Vicky,

The current miro link in your readme - https://miro.com/app/board/o9J_lbKPRv8=/ won't allow copying to a free miro account. It says "copying now allowed from previous source board".

Cheers, Tom.

**Comment by timja** [comment]
@tomf87 / @vickytnz I think this was fixed by Vicky just before by swapping it to a different board

**Comment by vickytnz** [comment]
Sorry about this @tomf87 for not noticing this earlier, I need to clear up my github notifications! Fixed now

**Comment by JodiB-TPR** [comment]
Hi, @vickytnz. I've just tried to do this and it still won't work. I tried both the "View this file in Miro" and the "...Design system elements" link in the README.

**Comment by vickytnz** [comment]
Just to check, can you right click on the board and then copy the board as per this? 
![image of miro whiteboard with board selected - menu shows options including copy](https://user-images.githubusercontent.com/1223264/149197819-f4812778-fd04-4b62-ade8-30d436ae3c38.png)

**Comment by JodiB-TPR** [comment]
Yes, I can do that, but it won't allow me to paste.
<img width="649" alt="Screen Shot 2022-01-13 at 9 38 02 AM" src="https://user-images.githubusercontent.com/74964198/149305046-2c75e870-bb40-48d4-9e85-1ba40851439c.png">

[forgot to tag you... @vickytnz]
